#include "../PCH.h"

namespace cl
{
bool _CheckCL(cl_int result, const char *file, int line)
{
	switch (result)
	{
	case (CL_SUCCESS):
		return true;
	case (CL_DEVICE_NOT_FOUND):
		WARNING("Error: CL_DEVICE_NOT_FOUND");
		break;
	case (CL_DEVICE_NOT_AVAILABLE):
		WARNING("Error: CL_DEVICE_NOT_AVAILABLE");
		break;
	case (CL_COMPILER_NOT_AVAILABLE):
		WARNING("Error: CL_COMPILER_NOT_AVAILABLE");
		break;
	case (CL_OUT_OF_RESOURCES):
		WARNING("Error: CL_OUT_OF_RESOURCES");
		break;
	case (CL_OUT_OF_HOST_MEMORY):
		WARNING("Error: CL_OUT_OF_HOST_MEMORY");
		break;
	case (CL_PROFILING_INFO_NOT_AVAILABLE):
		WARNING("Error: CL_PROFILING_INFO_NOT_AVAILABLE");
		break;
	case (CL_MEM_COPY_OVERLAP):
		WARNING("Error: CL_MEM_COPY_OVERLAP");
		break;
	case (CL_IMAGE_FORMAT_MISMATCH):
		WARNING("Error: CL_IMAGE_FORMAT_MISMATCH");
		break;
	case (CL_IMAGE_FORMAT_NOT_SUPPORTED):
		WARNING("Error: CL_IMAGE_FORMAT_NOT_SUPPORTED");
		break;
	case (CL_MISALIGNED_SUB_BUFFER_OFFSET):
		WARNING("Error: CL_MISALIGNED_SUB_BUFFER_OFFSET");
		break;
	case (CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST):
		WARNING("Error: CL_EXEC_STATUS_ERROR_FOR_EVENTS_IN_WAIT_LIST");
		break;
	case (CL_INVALID_VALUE):
		WARNING("Error: CL_INVALID_VALUE");
		break;
	case (CL_INVALID_DEVICE_TYPE):
		WARNING("Error: CL_INVALID_DEVICE_TYPE");
		break;
	case (CL_INVALID_PLATFORM):
		WARNING("Error: CL_INVALID_PLATFORM");
		break;
	case (CL_INVALID_DEVICE):
		WARNING("Error: CL_INVALID_DEVICE");
		break;
	case (CL_INVALID_CONTEXT):
		WARNING("Error: CL_INVALID_CONTEXT");
		break;
	case (CL_INVALID_QUEUE_PROPERTIES):
		WARNING("Error: CL_INVALID_QUEUE_PROPERTIES");
		break;
	case (CL_INVALID_COMMAND_QUEUE):
		WARNING("Error: CL_INVALID_COMMAND_QUEUE");
		break;
	case (CL_INVALID_HOST_PTR):
		WARNING("Error: CL_INVALID_HOST_PTR");
		break;
	case (CL_INVALID_MEM_OBJECT):
		WARNING("Error: CL_INVALID_MEM_OBJECT");
		break;
	case (CL_INVALID_IMAGE_FORMAT_DESCRIPTOR):
		WARNING("Error: CL_INVALID_IMAGE_FORMAT_DESCRIPTOR");
		break;
	case (CL_INVALID_IMAGE_SIZE):
		WARNING("Error: CL_INVALID_IMAGE_SIZE");
		break;
	case (CL_INVALID_SAMPLER):
		WARNING("Error: CL_INVALID_SAMPLER");
		break;
	case (CL_INVALID_BINARY):
		WARNING("Error: CL_INVALID_BINARY");
		break;
	case (CL_INVALID_BUILD_OPTIONS):
		WARNING("Error: CL_INVALID_BUILD_OPTIONS");
		break;
	case (CL_INVALID_PROGRAM):
		WARNING("Error: CL_INVALID_PROGRAM");
		break;
	case (CL_INVALID_PROGRAM_EXECUTABLE):
		WARNING("Error: CL_INVALID_PROGRAM_EXECUTABLE");
		break;
	case (CL_INVALID_KERNEL_NAME):
		WARNING("Error: CL_INVALID_KERNEL_NAME");
		break;
	case (CL_INVALID_KERNEL_DEFINITION):
		WARNING("Error: CL_INVALID_KERNEL_DEFINITION");
		break;
	case (CL_INVALID_KERNEL):
		WARNING("Error: CL_INVALID_KERNEL");
		break;
	case (CL_INVALID_ARG_INDEX):
		WARNING("Error: CL_INVALID_ARG_INDEX");
		break;
	case (CL_INVALID_ARG_VALUE):
		WARNING("Error: CL_INVALID_ARG_VALUE");
		break;
	case (CL_INVALID_ARG_SIZE):
		WARNING("Error: CL_INVALID_ARG_SIZE");
		break;
	case (CL_INVALID_KERNEL_ARGS):
		WARNING("Error: CL_INVALID_KERNEL_ARGS");
		break;
	case (CL_INVALID_WORK_DIMENSION):
		WARNING("Error: CL_INVALID_WORK_DIMENSION");
		break;
	case (CL_INVALID_WORK_GROUP_SIZE):
		WARNING("Error: CL_INVALID_WORK_GROUP_SIZE");
		break;
	case (CL_INVALID_WORK_ITEM_SIZE):
		WARNING("Error: CL_INVALID_WORK_ITEM_SIZE");
		break;
	case (CL_INVALID_GLOBAL_OFFSET):
		WARNING("Error: CL_INVALID_GLOBAL_OFFSET");
		break;
	case (CL_INVALID_EVENT_WAIT_LIST):
		WARNING("Error: CL_INVALID_EVENT_WAIT_LIST");
		break;
	case (CL_INVALID_EVENT):
		WARNING("Error: CL_INVALID_EVENT");
		break;
	case (CL_INVALID_OPERATION):
		WARNING("Error: CL_INVALID_OPERATION");
		break;
	case (CL_INVALID_GL_OBJECT):
		WARNING("Error: CL_INVALID_GL_OBJECT");
		break;
	case (CL_INVALID_BUFFER_SIZE):
		WARNING("Error: CL_INVALID_BUFFER_SIZE");
		break;
	case (CL_INVALID_MIP_LEVEL):
		WARNING("Error: CL_INVALID_MIP_LEVEL");
		break;
	case (CL_INVALID_GLOBAL_WORK_SIZE):
		WARNING("Error: CL_INVALID_GLOBAL_WORK_SIZE");
		break;
	default:
		return false;
	}

	return false;
}
} // namespace cl